export const data = [
  {
    id: 1,
    name: 'Daamin',
    species: 'Cat',
    available: false,
    birthYear: 2012,
    dateAdded: '19-06-2021',
    photoUrl: '/images/wpfirW7.jpg',
  },
  {
    id: 2,
    name: 'Dann',
    species: 'Dog',
    available: true,
    birthYear: 2016,
    dateAdded: '01-01-2022',
    photoUrl: '/images/ES0AHRx.jpg',
  },
  {
    id: 3,
    name: 'Annemie',
    species: 'Dog',
    available: true,
    birthYear: 2008,
    dateAdded: '25-04-2021',
    photoUrl: '/images/cL9Su9q.jpg',
  },
  {
    id: 4,
    name: 'Baxter',
    species: 'Cat',
    available: true,
    birthYear: 2020,
    dateAdded: '13-08-2021',
    photoUrl: '/images/uvkCHCy.jpg',
  },
  {
    id: 5,
    name: 'Beau',
    species: 'Cat',
    available: false,
    birthYear: 2013,
    dateAdded: '15-12-2021',
    photoUrl: '/images/dZXHXHn.jpg',
  },
  {
    id: 6,
    name: 'Echo',
    species: 'Dog',
    available: false,
    birthYear: 2019,
    dateAdded: '20-12-2021',
    photoUrl: '/images/KkxqmNs.jpg',
  },
  {
    id: 7,
    name: 'Arlo',
    species: 'Rat',
    available: true,
    birthYear: 2010,
    dateAdded: '27-01-2022',
    photoUrl: '/images/cw1ScXP.jpg',
  },
  {
    id: 8,
    name: 'Romeo',
    species: 'Dog',
    available: true,
    birthYear: 2015,
    dateAdded: '05-02-2021',
    photoUrl: '/images/7E8m93W.jpg',
  },
  {
    id: 9,
    name: 'Tank',
    species: 'Dog',
    available: false,
    birthYear: 2015,
    dateAdded: '05-08-2021',
    photoUrl: '/images/Q4CSFnX.jpg',
  },
  {
    id: 10,
    name: 'Henry',
    species: 'Cat',
    available: true,
    birthYear: 2009,
    dateAdded: '18-02-2021',
    photoUrl: '/images/wt5AGpR.jpg',
  },
  {
    id: 11,
    name: 'Coco',
    species: 'Dog',
    available: false,
    birthYear: 2007,
    dateAdded: '11-10-2021',
    photoUrl: '/images/AxzxKXk.jpg',
  },
  {
    id: 12,
    name: 'Riley',
    species: 'Dog',
    available: false,
    birthYear: 2018,
    dateAdded: '11-01-2022',
    photoUrl: '/images/xIqqOVz.jpg',
  },
  {
    id: 13,
    name: 'Ace',
    species: 'Dog',
    available: false,
    birthYear: 2018,
    dateAdded: '21-01-2021',
    photoUrl: '/images/N1ZEtEw.jpg',
  },
  {
    id: 14,
    name: 'Louie',
    species: 'Dog',
    available: true,
    birthYear: 2016,
    dateAdded: '23-07-2021',
    photoUrl: '/images/3sbNyva.jpg',
  },
  {
    id: 15,
    name: 'Toby',
    species: 'Cat',
    available: true,
    birthYear: 2019,
    dateAdded: '23-08-2021',
    photoUrl: '/images/gKGKsTg.jpg',
  },
  {
    id: 16,
    name: 'Mac',
    species: 'Cat',
    available: true,
    birthYear: 2014,
    dateAdded: '29-10-2021',
    photoUrl: '/images/1o7jhPf.jpg',
  },
  {
    id: 17,
    name: 'Murphy',
    species: 'Dog',
    available: true,
    birthYear: 2017,
    dateAdded: '29-05-2021',
    photoUrl: '/images/9c3OfRU.jpg',
  },
  {
    id: 18,
    name: 'Buster',
    species: 'Dog',
    available: 'Yes',
    birthYear: 2017,
    dateAdded: '12-01-2022',
    photoUrl: '/images/0FdlwHx.jpg',
  },
  {
    id: 19,
    name: 'Moose',
    species: 'Cat',
    available: false,
    birthYear: 2014,
    dateAdded: '14-01-2022',
    photoUrl: '/images/E24QYnz.jpg',
  },
  {
    id: 20,
    name: 'Bruno',
    species: 'Dog',
    available: true,
    birthYear: 2010,
    dateAdded: '19-01-2022',
    photoUrl: '/images/y5MOaAb.jpg',
  },
];
